apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-23T11:20:25Z"
  labels:
    app: tmt-web
  name: tmt-web
spec:
  containers:
  # Uvicorn
  - image: quay.io/testing-farm/tmt-web:latest
    args:
    - uvicorn
    name: uvicorn
    ports:
    - containerPort: 8000
      hostPort: 8100
    env:
    - name: VALKEY_URL
      value: valkey://valkey:6379
    - name: API_HOSTNAME
      value: http://tmt.staging.testing-farm.io
    # Valkey
  - image: docker.io/valkey/valkey:alpine
    name: valkey
    ports:
      - containerPort: 6379
        hostPort: 6379
