- hosts: all
  vars:
    pkg_retry_count: 5
    pkg_retry_delay: 30
  tasks:
  - name: Run guest-setup via profiles (non-image-mode)
    when: '"image-mode" not in IMAGE_NAME|lower'
    block:
    - name: Apply testing_farm_profiles.library.facts role
      ansible.builtin.include_role:
        name: testing_farm_profiles.library.facts

    - name: Apply testing_farm_profiles.library.time role
      when: ansible_virtualization_type not in ["container", "podman"]
      ansible.builtin.include_role:
        name: testing_farm_profiles.library.time

    - name: Apply testing_farm_profiles.library.epel role
      ansible.builtin.include_role:
        name: testing_farm_profiles.library.epel

    - name: Apply testing_farm_profiles.library.koji role
      ansible.builtin.include_role:
        name: testing_farm_profiles.library.koji

    - name: Apply testing_farm_profiles.library.tag_repository role
      ansible.builtin.include_role:
        name: testing_farm_profiles.library.tag_repository

  - name: Run original guest-setup (image-mode)
    when: '"image-mode" in IMAGE_NAME|lower'
    block:
    - include_tasks: update-and-restart.yaml
    - include_tasks: workaround-fedora-eln.yaml
    - include_tasks: workaround-fedora-rawhide.yaml
    - include_tasks: workaround-fedora-release.yaml
    - include_tasks: workaround-centos-7.yaml
    - include_tasks: workaround-centos-stream-8.yaml
    - include_tasks: workaround-dns.yaml
    - include_tasks: enable-crb.yaml
    - include_tasks: enable-powertools.yaml
    - include_tasks: install-epel.yaml
    - include_tasks: workaround-beakerlib.yaml
    - include_tasks: install-koji-brew.yaml
    # For EOL distros this can fail, ignore the fact tag repo is not around
    # It is considered a nice to have, but should not fail the setup.
    - include_tasks: tag-repository.yaml
      ignore_errors: true
    - include_tasks: set-timezone.yaml
