= Testing Farm Infrastructure
:data-uri:
:icons: font
:showtitle:
:source-highlighter: highlightjs
:toc:

This repository contains tools, configuration ands test used to maintain and setup Testing Farm's infrastrucutre.

The repository tries to bundle all required tools and provides an easy way how to set everything up for newcomers.

== Installation

The repository is managed via `direnv`.

. Add `.vault_pass` file with the known secret
+
[TIP]
====
See `Testing Farm` Bitwarden collection for the Vault passphrase.
====
+
[source,shell]
....
echo -n "VAULT_PASSWORD" > .vault_pass
....
+
. Install `direnv` and `poetry`
+
[source,shell]
....
$ sudo dnf -y install direnv poetry
....
. Hook `direnv` to your shell, see the https://direnv.net/docs/hook.html[official guide for more information].
. Allow `direnv` in this directory
+
[source,shell]
....
$ direnv allow
....

=== Reinstall

In some cases you might want to reinstall all the tools including the Python virtual environment.

. To reinstall the whole environment you can run:
+
[source,shell]
....
$ make clean
$ direnv allow
....
+
. To install only new python dependencies, use `poetry`
+
[source,shell]
....
$ poetry install
....

=== Usage

Enter this directory and `direnv` should take care of everything.

You can check if kubectl works

[source,shell]
....
$ kubectl version
....

== Tests

Tests are described via https://tmt.readthedocs.io/[`tmt`].

* to install tmt
+
[source,shell]
....
$ sudo dnf -y install tmt tmt-provision-virtual
....
+
* to list all available tests run
+
[source,shell]
....
$ tmt plan show
....
+
* to run all tests
+
[source,shell]
....
$ tmt run
....
