= Testing Farm Infrastructure
:data-uri:
:icons: font
:showtitle:
:source-highlighter: highlightjs
:toc:

This repository contains tools, configuration ands test used to maintain and setup Testing Farm's infrastrucutre. 

The repository tries to bundle all required tools and provides an easy way how to set everything up for newcomers.

== Installation

The repository is managed via Poetry which installs all required Python dependencies. For non-Python requirements a bootstrap script is provided which adds additional dependencies. Hopefully this script will be in the future deprecated by `tft-admin init` command.

. https://python-poetry.org/docs/#installation[Install Poetry]
. Install all Python requirements
+
[source,shell]
....
$ poetry install
....
+
. Add `.vault_pass` file with the known secret
+
[TIP]
====
Ask your colleagues if you are not sure what is the secret password.
====
+
[source,shell]
....
echo "SECRET_PASSWORD" > .vault_pass
....
+
. Run `bootstrap.sh` script, which make sure all other required tools work as expected
+
[source,shell]
....
$ poetry run ./bootstrap.sh
....

=== Usage

Before working activate the virtual environment via Poetry

[source,shell]
....
$ poetry shell
....

You can check if kubectl works

[source,shell]
....
$ kubectl version
....
