= Testing Farm Infrastructure
:data-uri:
:icons: font
:showtitle:
:source-highlighter: highlightjs
:toc:

This repository contains tools, configuration ands test used to maintain and setup Testing Farm's infrastrucutre.

The repository tries to bundle all required tools and provides an easy way how to set everything up for newcomers.

== Setup

The repository is managed via `direnv`. For setup:

* Add `.vault_pass` file with the known secret
+
[TIP]
====
Check Bitwarden for the vault password.
====
+
[source,shell]
....
echo "SECRET_PASSWORD" > .vault_pass
....
+
* Install `direnv`
+
[source,shell]
....
$ dnf -y install direnv
....
* Hook `direnv` to your shell, see the https://direnv.net/docs/hook.html[official guide for more information].
* Allow `direnv` in this directory
+
[source,shell]
....
$ direnv allow
....
+
[TIP]
====
In case of errors, investigate the setup log in `.direnv/envrc.log`
====
+
* Check if kubectl works and lists all available clusters:
+
[source,shell]
....
$ kubectl ctx
....

== Terraform

We use Terraform to provision infrastructure.

=== AWS EKS

To provision a infrastructure for development:

* enter the Terraform `dev` environment directory and initialize Terraform
+
[source,shell]
....
cd terraform/environments/dev
terraform init
....
+
* your development cluster name is set in `.envrc` file via the TF_VAR_cluster_name environemnt variable
+
[source,shell]
....
echo $TF_VAR_cluster_name
....
+
* create development environment with your own AWS EKS cluster
+
[source,shell]
....
terraform plan
terraform apply -auto-approve
....
+
* add cluster to your kubeconfig
+
[source,shell]
aws eks --region us-east-2 update-kubeconfig --name $TF_VAR_cluster_name
+
* develop & have fun
* tier down the infrastructure once happy
+
[source,shell]
....
terraform destroy -auto-approve
....
