= Testing Farm Infrastructure
:data-uri:
:icons: font
:showtitle:
:source-highlighter: highlightjs
:toc:

This repository contains tools, configuration ands test used to maintain and setup Testing Farm's infrastrucutre.

The repository tries to bundle all required tools and provides an easy way how to set everything up for newcomers.

== Setup

The repository is managed via `direnv`. For setup:

* Add `.vault_pass` file with the known secret
+
[TIP]
====
Check Bitwarden for the vault password.
====
+
[source,shell]
....
echo "SECRET_PASSWORD" > .vault_pass
....
+
* Install `direnv`
+
[source,shell]
....
$ dnf -y install direnv
....
* Hook `direnv` to your shell, see the https://direnv.net/docs/hook.html[official guide for more information].
* Allow `direnv` in this directory
+
[source,shell]
....
$ direnv allow
....
+
[TIP]
====
In case of errors, investigate the setup log in `.direnv/envrc.log`.
You can try to reinstall the environment by removing the `.direnv` directory and running `direnv allow`.
====
+
* Check if kubectl works and lists all available clusters:
+
[source,shell]
....
$ kubectl ctx
....

== Terraform

We use Terraform to provision infrastructure.

=== Development Environment

To provision a infrastructure for development:

* initialize the Terraform `dev` environment
+
[source,shell]
....
make init-dev
....
+
* create development environment with your own AWS EKS cluster and all available services in development mode
+
[source,shell]
....
make build-dev
....
+
* develop & have fun
* tier down the infrastructure once happy
+
[source,shell]
....
make destroy-dev
....
