---
#
# For documentation see:
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
#

plugin: amazon.aws.aws_ec2

cache: true
cache_plugin: ansible.builtin.jsonfile
cache_connection: .direnv/aws-cache

include_filters:
  - tag:Name:
      - "testing_farm_worker_*"

hostnames:
  - "tag:Name"
