#!/bin/bash -x

# Collect all output to pipeline.log file
exec > >(stdbuf -i0 -o0 tee pipeline.log) 2>&1

printf "\n[pipeline-start] $(date)\n\n"

export REQUEST_ID=$1

ARTIFACTS_URL="https://artifacts.dev.testing-farm.io"
API_URL="https://api.dev.testing-farm.io/v0.1"

[ -z "$REQUEST_ID" ] && { echo "No request ID given"; exit 1; }

REQUEST="$(curl -s --retry 5 $API_URL/requests/$REQUEST_ID)"

create_results_xml() {
    STATE=$1
    RESULT=$2
    RESULTS_XML=${3:-results.xml}

    cat > $RESULTS_XML <<EOF
<testsuites overall-result="$RESULT">
 <testsuite name="pipeline">
  <testcase name="$STATE" result="$RESULT">
   <logs>
     <log name="pipeline.log" href="${ARTIFACTS_URL}/${REQUEST_ID}/pipeline.log"/>
   </logs>
  </testcase>
 </testsuite>
</testsuites>
EOF
}

set_request_timeout() {
    REQUEST_TIMEOUT="$(echo "$REQUEST" | jq -r '.settings.pipeline.timeout | select (.!=null)')"
    [ -z "$REQUEST_TIMEOUT" ] && REQUEST_TIMEOUT="1440"
    REQUEST_TIMEOUT="${REQUEST_TIMEOUT}m"
    echo "Request timeout: $REQUEST_TIMEOUT"
}

set_citool_image() {
    CITOOL_IMAGE="$(echo "$REQUEST" | jq -r '.settings.worker.image | select (.!=null)')"
    [ -n "$CITOOL_IMAGE" ] && export CITOOL_IMAGE
}

# rpmlist on worker
rpm -qa > rpmlist-worker.txt

# create in progress page
create_results_xml in-progress skipped progress.xml

# deploy oculus viewer
curl -s --fail --retry 5 --show-error -o index.html https://gitlab.com/testing-farm/oculus/-/raw/main/results.html

set_request_timeout
set_citool_image

# run citool via container with a timeout
timeout --preserve-status --foreground --signal=SIGUSR1 $REQUEST_TIMEOUT \
citool-container.sh rules-engine \
                    testing-farm-request --request-id $REQUEST_ID \
                    archive \
                    hide-secrets \
                    ansible \
                    artemis \
                    fedora-copr:copr \
                    guest-setup-testing-farm:guest-setup \
                    guest-setup-order \
                    install-repository \
                    install-copr-build \
                    install-koji-build-execute \
                    git \
                    coldstore \
                    testing-farm-request-state-reporter \
                    test-schedule-tmt-connect:test-schedule-tmt \
                    test-scheduler-testing-farm \
                    test-schedule-runner \
                    test-schedule-report

# TFT-1721 - citool was not executed, exit non-zero to retry via Nomad
if [ ! -e "citool-debug.txt" ]; then
    echo -e "\033[31mError: citool was not run, request will be restarted!\033[0m" 1>&2
    exit 1
fi

# create pipeline error if no results.xml available
if [ ! -e "results.xml" ]; then
    create_results_xml failure error
fi

printf "\n[pipeline-end] $(date)"
