apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: ns
spec:
  caveats: |
    If fzf is installed on your machine, you can interactively choose
    between the entries using the arrow keys, or by fuzzy searching
    as you type.

    See https://github.com/ahmetb/kubectx for customization and details.
  description: |
    Also known as "kubens", a utility to set your current namespace and switch
    between them.
  homepage: https://github.com/ahmetb/kubectx
  platforms:
  - bin: kubens
    files:
    - from: kubectx-*/kubens
      to: .
    - from: kubectx-*/LICENSE
      to: .
    selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    sha256: 6df4def2caf5a9c291310124098ad6c4c3123936ddd4080b382b9f7930a233ec
    uri: https://github.com/ahmetb/kubectx/archive/v0.7.1.tar.gz
  shortDescription: Switch between Kubernetes namespaces
  version: v0.7.1
