#!/bin/bash -x

printf "\n[pipeline-start] $(date)\n\n"

export REQUEST_ID=$1
RUN_DIR=$2
TASK_NAME="tmt"

ARTIFACTS_HOSTNAME=artifacts.dev.testing-farm.io
ARTIFACTS_ROOT=/archive

PROGRESS_TICK=30

[ -z "$REQUEST_TIMEOUT" ] && REQUEST_TIMEOUT=12h

[ -z "$REQUEST_ID" ] && { echo "No request ID given"; exit 1; }
[ -z "$RUN_DIR" ] && { echo "No run directory given"; exit 1; }

REQUEST_ARCHIVE_DIR=${ARCHIVE_DIR}/${REQUEST_ID}

archive() {
    WHAT=$1
    WHERE=$2

    if [ ! -e $WHAT ]; then
        echo "Artifact '$WHAT' not found, skipping archivation"
        return
    fi

    rsync -avrz $WHAT ${ARTIFACTS_HOSTNAME}:${ARTIFACTS_ROOT}/${REQUEST_ID}/${WHERE}
}

create_results_xml() {
    STATE=$1
    RESULT=$2

    cat > results.xml <<EOF
<testsuites overall-result="$RESULT">
 <testsuite name="/pipeline">
  <testcase name="/$STATE" result="$RESULT">
   <logs>
     <log name="pipeline.log" href="https://artifacts.dev.testing-farm.io/${REQUEST_ID}/pipeline.log"/>
   </logs>
  </testcase>
 </testsuite>
</testsuites>
EOF
}

create_results_html() {
    # citool exposes all output to stderr, archive it as the pipeline log
    archive ${RUN_DIR}/logs/${TASK_NAME}.stderr.0 pipeline.log

    tfxunit2junit.py --issues-url https://gitlab.com/testing-farm/general/-/issues results.xml > results-junit.xml || true
    testing-farm-viewer -r results-junit.xml -t "results" || true
    archive results-junit.xml
    archive index.html
}

# create archive directory
if [ -z "$NO_ARCHIVE" ]; then
    ssh $ARTIFACTS_HOSTNAME mkdir -p ${ARTIFACTS_ROOT}/${REQUEST_ID}
fi

# rpmlist on worker
rpm -qa > rpmlist-worker.txt

# create in progress page
create_results_xml in-progress passed

# disable bash debug until we run tmt with the progress reporting
set +x

# start syncing in background
if [ -z "$NO_ARCHIVE" ]; then
    { while true; do create_results_html &>> progress.log; sleep $PROGRESS_TICK; done; } &
fi

# run citool via container with a timeout
timeout --preserve-status --foreground --signal=SIGUSR1 $REQUEST_TIMEOUT \
citool-container.sh hide-secrets \
                    rules-engine-empty:rules-engine \
                    testing-farm-request --request-id $REQUEST_ID \
                    ansible \
                    artemis \
                    fedora-copr:copr \
                    guest-setup-testing-farm:guest-setup \
                    install-copr-build \
                    install-koji-build-execute \
                    install-repository \
                    guess-environment-testing-farm-request:guess-environment \
                    dist-git-testing-farm:dist-git \
                    coldstore \
                    testing-farm-request-state-reporter \
                    test-schedule-tmt-connect:test-schedule-tmt \
                    test-scheduler \
                    test-schedule-runner \
                    test-schedule-report

# skip archivation
[ -n "$NO_ARCHIVE" ] && exit

# kill the progress
kill $!

# progress is over, enable back bash debug mode
set -x

# create pipeline error if no results.xml available
if [ ! -e "results.xml" ]; then
    create_results_xml failure error
fi

# sync task logs
TASK_DIR=$(dirname $RUN_DIR)
for path in ${TASK_DIR}/${TASK_NAME}/*; do
    archive $path
done

# sync kernel buffers on artifacts storage
# TFT-894
ssh artifacts.dev.testing-farm.io sync

create_results_html

printf "\n[pipeline-end] $(date)"

# save stdout and stderr at the end
archive ${RUN_DIR}/logs/${TASK_NAME}.stdout.0 job.log
archive ${RUN_DIR}/logs/${TASK_NAME}.stderr.0 pipeline.log
