- hosts: all
  vars:
    pkg_retry_count: 5
    pkg_retry_delay: 30
  module_defaults:
    ansible.builtin.package:
      use: "{{ _pkg_module | default('auto') }}"
  tasks:
    - include_tasks: install-python.yaml
      when:
        - '"auto-osbuild" not in IMAGE_NAME|lower'
        - '"pfmt" not in IMAGE_NAME|lower'
        - '"image-mode" not in IMAGE_NAME|lower'
    # DO NOT ENABLE BY DEFAULT, IT BREAKS PYTHON TEST SUITE (and can others)
    # - include_tasks: nosync.yaml
    - include_tasks: update-and-restart.yaml
    - include_tasks: workaround-fedora-eln.yaml
    - include_tasks: workaround-fedora-rawhide.yaml
    - include_tasks: workaround-fedora-release.yaml
    - name: testing_farm_profiles.workarounds.centos_eol
      when:
        - '"auto-osbuild" not in IMAGE_NAME|lower'
        - '"pfmt" not in IMAGE_NAME|lower'
      ansible.builtin.include_role:
        name: testing_farm_profiles.workarounds.centos_eol
    - name: testing_farm_profiles.workarounds.dns
      when:
        - '"auto-osbuild" not in IMAGE_NAME|lower'
        - '"pfmt" not in IMAGE_NAME|lower'
      ansible.builtin.include_role:
        name: testing_farm_profiles.workarounds.dns
    - name: testing_farm_profiles.repository.crb
      when:
        - '"auto-osbuild" not in IMAGE_NAME|lower'
        - '"pfmt" not in IMAGE_NAME|lower'
      ansible.builtin.include_role:
        name: testing_farm_profiles.repository.crb
    - name: testing_farm_profiles.repository.epel
      when:
        - '"auto-osbuild" not in IMAGE_NAME|lower'
        - '"pfmt" not in IMAGE_NAME|lower'
      ansible.builtin.include_role:
        name: testing_farm_profiles.repository.epel
    - include_tasks: workaround-beakerlib.yaml
    - include_tasks: install-koji-brew.yaml
    # For EOL distros this can fail, ignore the fact tag repo is not around
    # It is considered a nice to have, but should not fail the setup.
    - include_tasks: tag-repository.yaml
      ignore_errors: true
    - name: testing_farm_profiles.library.time
      when:
        - '"auto-osbuild" not in IMAGE_NAME|lower'
        - '"pfmt" not in IMAGE_NAME|lower'
      ansible.builtin.include_role:
        name: testing_farm_profiles.library.time
      vars:
        # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configure-ec2-ntp.html
        time_ntp_server: 169.254.169.123
