---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server
  name: server
spec:
  initContainers:
    - name: config
      image: quay.io/testing-farm/config:latest
      volumeMounts:
        - name: config-volume
          mountPath: /api
    - name: ranch-public
      image: quay.io/testing-farm/ranch-public:latest
      volumeMounts:
        - name: ranch-public-volume
          mountPath: /api
    - name: waitdb
      image: quay.io/testing-farm/api:latest
      args:
        - waitdb
      volumeMounts:
        - name: config-volume
          mountPath: /etc/testing-farm/api
        - name: ranch-public-volume
          mountPath: /etc/testing-farm/ranch-public/api
    - name: createdb
      image: docker.io/cockroachdb/cockroach:v23.2.4
      command:
        - sh
      args:
        - -c
        - cockroach sql --insecure --url postgresql://root@cockroach:26257 -e "CREATE DATABASE nucleus" || true
    - name: initdb
      image: quay.io/testing-farm/api:latest
      args:
        - initdb
      volumeMounts:
        - name: config-volume
          mountPath: /etc/testing-farm/api
        - name: ranch-public-volume
          mountPath: /etc/testing-farm/ranch-public/api
  containers:
    - name: api-public
      image: quay.io/testing-farm/api:latest
      args:
        - public
      ports:
        - containerPort: 8001
          hostPort: 8001
      volumeMounts:
        - name: config-volume
          mountPath: /etc/testing-farm/api
        - name: ranch-public-volume
          mountPath: /etc/testing-farm/ranch-public/api
    - name: api-internal
      image: quay.io/testing-farm/api:latest
      args:
        - internal
      env:
        - name: TF_API_PORT
          value: "8002"
      ports:
        - containerPort: 8002
          hostPort: 8002
      volumeMounts:
        - name: config-volume
          mountPath: /etc/testing-farm/api
        - name: ranch-public-volume
          mountPath: /etc/testing-farm/ranch-public/api
    - name: dispatcher
      image: quay.io/testing-farm/dispatcher:latest
      env:
        - name: TF_DISPATCHER_PUBLIC_URL
          value: "http://api-public:8001"
        - name: TF_DISPATCHER_INTERNAL_URL
          value: "http://api-internal:8002"
  volumes:
    - name: config-volume
      emptyDir: {}
    - name: ranch-public-volume
      emptyDir: {}
