---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server
  name: server
spec:
  initContainers:
    - args:
        - initdb
      env:
        - name: TF_API_PORT
          value: "8001"
        - name: TF_API_DATABASE_HOST
          value: 0.0.0.0
        - name: TF_API_DATABASE_PORT
          value: "26257"
        - name: TF_API_DATABASE_USER
          value: root
      image: quay.io/testing-farm/api:latest
      name: api-public
  containers:
    - args:
        - public
      env:
        - name: TF_API_PORT
          value: "8001"
        - name: TF_API_DATABASE_HOST
          value: 0.0.0.0
        - name: TF_API_DATABASE_PORT
          value: "26257"
        - name: TF_API_DATABASE_USER
          value: root
      image: quay.io/testing-farm/api:latest
      name: api-public
    - args:
        - internal
      env:
        - name: TF_API_PORT
          value: "8002"
        - name: TF_API_DATABASE_HOST
          value: 0.0.0.0
        - name: TF_API_DATABASE_USER
          value: root
        - name: TF_API_DATABASE_PORT
          value: "26257"
      image: quay.io/testing-farm/api:latest
      name: api-internal
    - env:
        - name: TF_DISPATCHER_PUBLIC_URL
          value: "http://api-public:8001"
        - name: TF_DISPATCHER_INTERNAL_URL
          value: "http://api-internal:8002"
      image: quay.io/testing-farm/dispatcher:latest
      name: dispatcher
