---
- name: Create nomad user
  become: true
  user:
    name: "{{ nomad_user }}"
    system: true
    create_home: true
    home: "{{ nomad_home_dir }}"
    shell: /bin/bash
  when:
    - nomad_user != "root"

- name: Install required packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nomad_os_packages }}"

- name: Create Nomad download directory
  file:
    state: directory
    path: "nomad-download"
    mode: 0755
  register: download

- name: Download Nomad
  command: "curl -Lo {{ download.path }}/{{ nomad_pkg }} {{ nomad_zip_url }}"
  tags:
    - skip_ansible_lint

- name: Unarchive Nomad
  unarchive:
    src: "{{ download.path }}/{{ nomad_pkg }}"
    dest: "{{ download.path }}"
    creates: "{{ download.path }}/nomad"
    remote_src: true

- name: Install Nomad
  become: true
  copy:
    src: "{{ download.path }}/nomad"
    dest: "{{ nomad_bin_dir }}"
    owner: root
    group: root
    mode: 0755
    remote_src: true

- name: Create Nomad plugin directory
  become: true
  file:
    path: "{{ nomad_plugin_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download Nomad podman driver
  command: "curl -Lo {{ download.path }}/{{ nomad_driver_podman_pkg }} {{ nomad_driver_podman_zip_url }}"
  tags:
    - skip_ansible_lint

- name: Unarchive Nomad podman driver
  become: true
  unarchive:
    src: "{{ download.path }}/{{ nomad_driver_podman_pkg }}"
    dest: "{{ download.path }}"
    remote_src: true

- name: Install Nomad podman driver
  become: true
  copy:
    src: "{{ download.path }}/nomad-driver-podman"
    dest: "{{ nomad_plugin_dir }}/nomad-driver-podman"
    owner: root
    group: root
    mode: 0755
    remote_src: true

- name: Cleanup
  file:
    path: "{{ download.path }}"
    state: "absent"
