---
- name: Render Jinja templates
  hosts: localhost
  tasks:
    - name: Render server.bu
      ansible.builtin.template:
        src: server.bu.j2
        dest: server.bu

    - name: Render API reverse proxy config
      ansible.builtin.template:
        src: "{{ ansible_env.PROJECT_ROOT }}/terragrunt/environments/dev/server/pods/nginx/api.dev-USER.testing-farm.io.conf.j2"
        dest: "{{ ansible_env.PROJECT_ROOT }}/terragrunt/environments/dev/server/pods/nginx/api.dev-{{ ansible_env.USER }}.testing-farm.io.conf"

    - name: Render Internal API reverse proxy config
      ansible.builtin.template:
        src: "{{ ansible_env.PROJECT_ROOT }}/terragrunt/environments/dev/server/pods/nginx/internal.api.dev-USER.testing-farm.io.conf.j2"
        dest: "{{ ansible_env.PROJECT_ROOT }}/terragrunt/environments/dev/server/pods/nginx/internal.api.dev-{{ ansible_env.USER }}.testing-farm.io.conf"

    - name: Render Nomad reverse proxy config
      ansible.builtin.template:
        src: "{{ ansible_env.PROJECT_ROOT }}/terragrunt/environments/dev/server/pods/nginx/nomad.dev-USER.testing-farm.io.conf.j2"
        dest: "{{ ansible_env.PROJECT_ROOT }}/terragrunt/environments/dev/server/pods/nginx/nomad.dev-{{ ansible_env.USER }}.testing-farm.io.conf"
